### ISSUE TITLE
yarn不了啊，亲

### ISSUE THREAD

**Issue by ffywhxf** [williamnie/umi-electron#1]
error An unexpected error occurred: "http://registry.npm.souche-inc.com/mime-types/download/mime-types-2.1.21.tgz: Request failed \"403 Forbidden\"".
info If you think this is a bug, please open a bug report with the information provided in "F:\\xiangmu\\umi-electron-master\\yarn-error.log".
info Visit https://yarnpkg.com/en/docs/cli/install for documentation about this command.

**Comment by xclw2000** [comment]
我也遇到了同样的问题，作者出来回个话呀

**Comment by williamnie** [comment]
把yarn.lock删除了试试，切换成淘宝源，由于网络问题有些包装不上

**Comment by williamnie** [comment]
> 我也遇到了同样的问题，作者出来回个话呀

现在可以了么？

**Comment by xclw2000** [comment]
yarn start:renderer
yarn run v1.13.0
$ APP_ROOT=src/renderer umi dev
'APP_ROOT' 不是内部或外部命令，也不是可运行的程序或批处理文件。
