### ISSUE TITLE
yarn start报错

### ISSUE THREAD

**Issue by xclw2000** [williamnie/umi-electron#2]
![image](https://user-images.githubusercontent.com/32091566/61272927-df258d00-a7da-11e9-8cd4-ec757f5dc00a.png)

**Comment by williamnie** [comment]
你是windows电脑吧？我加上了cross-env，package里面应该有这个包，直接git pull 再试试，不行的话，装下cross-env，并在APP_ROOT前面加上cross-env。

**Comment by xclw2000** [comment]
可以了，谢谢
